# Generated by Django 5.2.3 on 2025-06-19 02:30

import django.contrib.gis.db.models.fields
import taggit.managers
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        (
            "taggit",
            "0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Measurements",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("meter_ID", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("lat_lon", django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ("timestamp", models.DateTimeField(auto_now=True)),
                ("wind_direction", models.IntegerField()),
                ("wind_speed", models.FloatField()),
                (
                    "tags",
                    taggit.managers.TaggableManager(
                        help_text="A comma-separated list of tags.",
                        through="taggit.TaggedItem",
                        to="taggit.Tag",
                        verbose_name="Tags",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("wind_direction__gte", 1), ("wind_direction__lt", 360)
                        ),
                        name="Wind Direction",
                    )
                ],
            },
        ),
    ]
